# Welcome to Jekyll!

# Website settings
title: "PlayNG's Blog"
description: "PlayNG's blog, Follow up with us in our hilarious but yet serious opinions."
keywords: "PlayNG. PlayNG Online"
baseurl: "/"
url: "http://www.playngonline.com"
# url: "http://127.0.0.1:4000"

# blog img path
#img_path: 'http://www.jack003.com/static/img/blog'

# author
author:
  name: 'PlayNG'
  first_name: 'Online'
  last_name: 'PlayNG'
  email: 'music@playngonline.com'
  facebook_username: ''
  github_username: ''
  head_img: 'static/img/landing/logo.png'

# social link
#jingyu:
#  first_name: 'Yu'
#  last_name: 'Jing'
#  description: 'Painter.'
#  link: 'http://angular.jack003.com'
#  email: '805963294@qq.com'

# landing page
#landing:
#  home: 'Web'
#  about: 'About'
#  career: 'Career'
#  skills: 'Skills'
#  projects: 'Project'
#  blog: 'Blog'
#  link: 'Link'


# blog index
index:
  home: 'Home'
  reviews: 'Reviews'
  info: 'Info'
  gists: 'Gists'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
#changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
#ba:
#  uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
