# Welcome to Jekyll!

# Website settings
title: "PlayNG's Blog"
description: "PlayNG's blog, Follow up with us in our hilarious but yet serious opinions."
keywords: "PlayNG. PlayNG Online"
baseurl: "/"
url: "http://www.playngonline.com"
# url: "http://127.0.0.1:4000"

# blog img path
#img_path: 'http://www.playng.github.io/static/img/blog'

# author
author:
  name: 'PlayNG'
  first_name: 'Online'
  last_name: 'PlayNG'
  email: 'music@playngonline.com'
  facebook_username: ''
  twitter_username: ''
  instagram_username: ''
  github_username: 'PlayNG'
  head_img: 'static/img/landing/logo.png'


# blog index
index:
  home: 'Home'
  reviews: 'Reviews'
  info: 'Info'
  gists: 'Gists'
  lyrics: 'Lyrics'

disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# google analytics
ga:
  id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
